### ISSUE TITLE
Cloning build from Github results in SASS compiling error

### ISSUE THREAD

**Issue by jj-owens** [Gottwik/Enduro#153]
Apologies in advance if this information is available somewhere.

I have a site which is up and running and wished to make edits. I cloned the Github to my local machine and ran `npm install`. I also ran `bower install` just in case. `npm install` resulted in the following lines of note:

npm WARN lifecycle enduro_mirror@1.0.0~postinstall: cannot run in wd %s %s (wd=%s) enduro_mirror@1.0.0 ./node_modules/bower/bin/bower install /home/******/dev/v2port
npm WARN enduro_mirror@1.0.0 No repository field.

Upon running `enduro dev`, I receive the following error while it is attempting to compile the SASS:

▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼ Sass error ▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼
assets/css/vendor/bootstrap_selection.scss
Error: File to import not found or unreadable: ../../vendor/bootstrap/scss/normalize.
       Parent style sheet: /home/*****/dev/v2port/assets/css/vendor/bootstrap_selection.scss
        on line 5 of assets/css/vendor/bootstrap_selection.scss
>> @import '../../vendor/bootstrap/scss/normalize';
   ^

▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲

Any thoughts? I've tried installing jquery and bootstrap locally (globally).  I also used `enduro theme` to create a new mirror starter page and had no issues there, everything was normal.

I appreciate your time and assistance.

~J

**Comment by Gottwik** [comment]
this is my fault not specifying exact bootstrap version. could you try to clone again(or just pull) on the enduro mirror theme and install bower again and this should work just fine.

let us know if this got resolved for you 😄

**Comment by jj-owens** [comment]
Update:

The `bootstrap_selection.scss` file is pointing towards these for input:

`// Core variables and mixins
@import '../../vendor/bootstrap/scss/variables';

// Reset and dependencies
@import '../../vendor/bootstrap/scss/normalize';
@import '../../vendor/bootstrap/scss/mixins';

// Core CSS
// @import '../../vendor/bootstrap/scss/reboot';
@import '../../vendor/bootstrap/scss/grid';

// Utility classes
@import '../../vendor/bootstrap/scss/utilities';

// Images
@import '../../vendor/bootstrap/scss/images';
`

However, in my directory, it doesn't appear that these actually exist. Going to research how to fix this.
Really need to make edits to this site, these bugs are unfortunate. :(

**Comment by jj-owens** [comment]
Tried creating a NEW enduro project in a different directory, because as of a couple days ago- this was working fine and I could create a new theme. Was going to look for differences, but now creating a new project throws this bower error:

┌—————————————————~—Enduro theme service—~—————————————————┐
? choose a theme mirror
│ getting info for 'mirror' theme                        ✓ │
? choose project name: testing
? choose your admin login: test
? choose your admin password: [hidden]
│ downloading and extracting theme                       ✓ │
│ setting up admin credentials                           ✓ │
│ getting project dependencies                           ✓ │
│ installing npm dependencies                            ✓ │
/home/jjowens/code/testing/node_modules/bower/lib/node_modules/q/q.js:155
                throw e;
                ^

SyntaxError: Unexpected token @ in JSON at position 0
    at JSON.parse (<anonymous>)
    at /home/jjowens/code/testing/node_modules/bower/lib/node_modules/bower-json/lib/json.js:42:29
    at /home/jjowens/code/testing/node_modules/bower/lib/node_modules/graceful-fs/graceful-fs.js:78:16
    at /usr/lib/node_modules/enduro/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:505:3)

**Comment by jj-owens** [comment]
Been trying to find a fix for this for the entire week, can anyone help, please?

Is this part of the problem?

https://github.com/twbs/bootstrap/issues/24068

It appears bower should no longer be used to install bootstrapv4.

Is there a workaround?

**Comment by jj-owens** [comment]
bower bootstrap#4                       EMALFORMED Failed to read C:\Users\JJA1D4~1.OWE\AppData\Local\Temp\NITRO-jj.owens\bower\ca4c50b905dc21ea17a10549a6f5944f-9772-JU3cfY\bower.json

Additional error details:
Unexpected token @ in JSON at position 0

**Comment by jj-owens** [comment]
Ok,
    This is the workaround that finally worked for me:

- change paths in the `assets/css/vender/bootstrap_selection.scss` file to import directly from the node_modules folder located in the root project path, such as:
`@import '../../../node_modules/bootstrap/scss/normalize'`
- add bootstrap to package.json
- remove bootstrap from bower.json in the project root directory such that:

`"dependencies": {
    "jquery": "^3.1.1",
    "requirejs": "^2.3.2",
    "kiskabricks_wedgecss": "^1.0.0",
    "font-awesome": "^4.7.0"
  }
`
- after those steps run `bower install` from the root project directory. 
- once that is complete, run `enduro dev` and voila, no more sass compilation error! 

This probably isn't best practice- but it's what worked for me after trying so many different methods. Hopefully this helps run down the actual problem?

~J
