### ISSUE TITLE
Content won't load properly if root folder name ends in "cms"

### ISSUE THREAD

**Issue by havaslondon** [Gottwik/Enduro#219]
The regex in `/libs/global_data.js`:

`const fileInCms = file.match(/cms\/(.*)\.([^\\/]+)$/)[1]`

will, given the following path:

`/path/to/my-site-cms/cms/global/global.js`

set `fileInCms` to be:

`cms/global/global`

... which will cause the site to fail to load its global config files.

Obviously there's a simple fix; rename your root folder to not end in "cms". But in case anyone else is getting weird errors about there not being any admin users or only loading some content...

**Comment by GiovanniFrigo** [comment]
Getting it also here. I think this is a pretty big issue, as it's common to call a cms project.. well, cms.

For the sake of github issues indexing (I couldn't find this issue myself), I'll post the error given in terminal when the root folder name ends in `cms`.

The project will compile and start just fine, but when accessing to the admin interface you'll get the following output: 
```
Error: ENOENT: no such file or directory, stat '[...]/new-cms/_generated/_prebuilt/_settings.css.html'
TypeError: Cannot set property 'juicebox_enabled' of undefined
    at api_call.call ([...]/lib/node_modules/enduro/libs/admin_api/get_application_settings.js:14:40)
    at admin_api.call ([...]/lib/node_modules/enduro/libs/admin_api.js:20:38)
````

And on the web page itself, you'll see the message `Eh, there are no admin users. Add some by running enduro admin add <usr> <pass> in the console.` even if there are some.
