### ISSUE TITLE
Enduro Quill installation failed

### ISSUE THREAD

**Issue by Steven-lim1412** [Gottwik/Enduro#230]
Hi,

As per title, having issue with Quill installation. My existing enduro setup will throw the following error

│ starting npm                                           ✓ │
│ enduro_quill installed successfully                      │
Unhandled rejection TypeError: Cannot read property 'default_settings' of undefined
    at add_brick_settings (C:\Users\Steve\AppData\Roaming\npm\node_modules\enduro\libs\actions\install.js:68:62)
    at install_brick_via_npm.then (C:\Users\Steve\AppData\Roaming\npm\node_modules\enduro\libs\actions\install.js:21:11)
    at tryCatcher (C:\Users\Steve\AppData\Roaming\npm\node_modules\enduro\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Steve\AppData\Roaming\npm\node_modules\enduro\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Steve\AppData\Roaming\npm\node_modules\enduro\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Steve\AppData\Roaming\npm\node_modules\enduro\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Steve\AppData\Roaming\npm\node_modules\enduro\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Steve\AppData\Roaming\npm\node_modules\enduro\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Steve\AppData\Roaming\npm\node_modules\enduro\node_modules\bluebird\js\release\async.js:143:10)

If i were to run the install on a fresh Enduro install, I will not get the error but I wont be seeing the RTE. Any idea?

-Steven

**Comment by rnlambert7** [comment]
What version of Enduro are you running? It's not documented yet but you need version 1.4.45 in order to use brick settings from enduro.json.

I have an issue in place currently for a version test for enduro bricks here: https://github.com/Gottwik/Enduro/issues/218

This may explain why a fresh install is working for you but your current isn't.

**Comment by Steven-lim1412** [comment]
even with a fresh enduro install and successful brick install, the Quill UI is not appearing. I noticed there are tickets opened for it. Nevertheless, I managed to get this to work, while not ideal, I used the Quil sample project and migrate/overlay my changes accordingly. 

as for the version for my broken setup, I believe is also 1.4.45. I have just started the project 24 Jan 2018
