### ISSUE TITLE
Enduro js don't create new project.

### ISSUE THREAD

**Issue by mmss1995** [Gottwik/Enduro#337]
I installed enduro with `npm install enduro -g` in my cmd terminal. It install correctly, when I type `enduro --version `, print out `1.4.47`.
Well, everything right, but when I type `enduro create helloworld` in line to [enduro startup tutorlial](https://www.endurojs.com/docs/hello-world) cmd sad:

> (node:4424) UnhandledPromiseRejectionWarning: ReferenceError: primordials is not defined
>     at fs.js:27:26
>     at req_ (C:\Users\matte\AppData\Roaming\npm\node_modules\enduro\node_modules\natives\index.js:143:24)
>     at Object.req [as require] (C:\Users\matte\AppData\Roaming\npm\node_modules\enduro\node_modules\natives\index.js:55:10)
>     at Object.<anonymous> (C:\Users\matte\AppData\Roaming\npm\node_modules\enduro\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
>     at Module._compile (internal/modules/cjs/loader.js:959:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
>     at Module.load (internal/modules/cjs/loader.js:815:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
>     at Module.require (internal/modules/cjs/loader.js:852:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (C:\Users\matte\AppData\Roaming\npm\node_modules\enduro\node_modules\vinyl-fs\node_modules\graceful-fs\graceful-fs.js:3:27)
>     at Module._compile (internal/modules/cjs/loader.js:959:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
>     at Module.load (internal/modules/cjs/loader.js:815:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
>     at Module.require (internal/modules/cjs/loader.js:852:19)
> (node:4424) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:4424) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

So, I think, is a dependence of endoru-js, but after installed python, updated npm and node, the situation is still the same. 

Some advice?

**Comment by dendyjoom** [comment]
I also ran into this problem. Did anyone manage to solve this?
Mac OS 10.15
node v12.6.0

**Comment by gcornejo** [comment]
I researched, and found out that gulp 3 is no longer supporter.
https://github.com/gulpjs/gulp/issues/2324
I guess Enduro JS will require an update to gulp 4, and seems like it´s not that straight forward. The configuration files aren´t compatible.
Hope someone sorts this out.

**Comment by mmss1995** [comment]
> I researched, and found out that gulp 3 is no longer supporter.
> [gulpjs/gulp#2324](https://github.com/gulpjs/gulp/issues/2324)
> I guess Enduro JS will require an update to gulp 4, and seems like it´s not that straight forward. The configuration files aren´t compatible.


And so we only need to wait the gulp 4? Really? 😢

**Comment by LucasMW** [comment]
Same problem here;
How can I try enduro?
enduro --version
1.4.47
node --version
v13.7.0

Unhandled rejection ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (/usr/local/lib/node_modules/enduro/node_modules/natives/index.js:143:24)

**Comment by gcornejo** [comment]
Maybe an alternative, which I'll try is to install several versions of nodejs, with NVM:
https://codeforgeek.com/run-multiple-node-js-apps-with-different-node-js-version-in-same-server/
NVM = Node Version Manager
https://github.com/nvm-sh/nvm
Hope it helps others to run node with previous version, and get enduro running

**Comment by Ezra-Siton-UIX** [comment]
This project is still maintained? The last commit was before a `year ago`.
Also, get this error.

```
Unhandled rejection ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (C:\Users\Siton\AppData\Roaming\npm\node_modules\enduro\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\Siton\AppData\Roaming\npm\node_modules\enduro\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\Siton\AppData\Roaming\npm\node_modules\enduro\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Siton\AppData\Roaming\npm\node_modules\enduro\node_modules\vinyl-fs\node_modules\graceful-fs\graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
```

**Comment by Ezra-Siton-UIX** [comment]
Looks like `node.js` support issue. 


I install my site on 2 laptops:
- **New laptop:** Not working (Node 12)
- **Old laptop:** Works fine (Node 8)

**Test:** I update node version on my old laptop to last stable node js (12.16.1) and now - no command is working (Throw errors). 

Related:
https://github.com/Gottwik/Enduro/issues/330

**Comment by fqmonte** [comment]
Not work
