### ISSUE TITLE
installing in ubuntu 16 failed

### ISSUE THREAD

**Issue by acebesmonte** [Gottwik/Enduro#34]
`looper@looper-pc:~/spheria$ sudo npm install enduro -g
[sudo] password for looper: 
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
/usr/bin/enduro -> /usr/lib/node_modules/enduro/cli.js
/usr/lib
└─┬ enduro@1.4.13 
  └── promised-handlebars@2.0.1  (git+https://github.com/Gottwik/promised-handlebars.git#b19dc6dbbcaf8722ad3c0bfee6e04affbe9d1c7b)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/enduro/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
looper@looper-pc:~/spheria$ enduro create endurocms
Unhandled rejection Error: ENOENT: no such file or directory, scandir '/usr/lib/node_modules/enduro/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.getInstalledBinaries (/usr/lib/node_modules/enduro/node_modules/node-sass/lib/extensions.js:123:13)
    at foundBinariesList (/usr/lib/node_modules/enduro/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/usr/lib/node_modules/enduro/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/usr/lib/node_modules/enduro/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/usr/lib/node_modules/enduro/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/usr/lib/node_modules/enduro/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/enduro/node_modules/gulp-sass/index.js:187:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)`

**Comment by acebesmonte** [comment]
looper@looper-pc:~/Documents$ npm --v
3.10.10
looper@looper-pc:~/Documents$ node -v
v6.10.0

**Comment by Gottwik** [comment]
Hey @acebesmonte, could you check what is in the `/usr/lib/node_modules` folder? is enduro there? is node-sass there?

**Comment by Gottwik** [comment]
Hey @acebesmonte Did you manage to resolve this? Let me know I am happy to help.

**Comment by Gottwik** [comment]
Hey I am going to go ahead and close this issue. Feel free to reopen if you didn't manage to resolve your issue.

**Comment by andreperegrina** [comment]
Hi, i have the same problem, is there a way to solved?
