### ISSUE TITLE
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by keith24** [Gottwik/Enduro#68]
Just trying to create a new project.  

```sh
keith24:~/workspace (master) $ sudo n stable
   installed : v4.6.1

keith24:~/workspace (master) $ enduro create myproject
Unhandled rejection SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/enduro/libs/actions/developer_start.js:12:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/enduro/libs/linker/linker.js:74:35
```

**Comment by Gottwik** [comment]
Um, is there any reason why you want to use node 4? Updating would solve this. Do you think we should keep support for 4?

**Comment by keith24** [comment]
I think my n is broken: 

```sh
keith24:~/workspace (master) $ sudo n 6.11.0

     install : node-v6.11.0
       mkdir : /usr/local/n/versions/node/6.11.0
       fetch : https://nodejs.org/dist/v6.11.0/node-v6.11.0-linux-x64.tar.gz
######################################################################## 100.0%
   installed : v4.6.1

keith24:~/workspace (master) $ node --version
v4.6.1
```

I am using [cloud9](https://c9.io), which [uses nvm](https://community.c9.io/t/how-to-update-node-js/1273/2?u=keith7), so that's probably why.  I used nvm to update to 6.11.0. 

I don't think you need to support older versions, but you might want to catch the error and display a message and/or mention that you need node vx.x.x+ in the readme.  

Now I'm getting a new error: 

```sh
keith24:~/workspace (master) $ enduro create myproject
Unhandled rejection Error: Cannot find module 'less-plugin-autoprefix'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v6.11.0/lib/node_modules/enduro/libs/build_tools/less_handler.js:4:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at css_handler.init (/home/ubuntu/.nvm/versions/node/v6.11.0/lib/node_modules/enduro/libs/build_tools/css_handler.js:12:21)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v6.11.0/lib/node_modules/enduro/gulpfile.js:26:81)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v6.11.0/lib/node_modules/enduro/libs/actions/developer_start.js:13:12)
```

Should I open a new issue?

**Comment by Gottwik** [comment]
Aaah, the less autoprefixer was added as devDependency. I fixed it, could you update enduro (`npm i enduro -g`). Should be good to go.

I also updated node dependency to 6+ so other people won't experience the es6 error.

**Comment by keith24** [comment]
Working now.

**Comment by Gottwik** [comment]
glad to hear it's working for you. Let us know if you had other issues/ideas :-)
