### ISSUE TITLE
enduro error installing

### ISSUE THREAD

**Issue by TheFenixfx** [Gottwik/Enduro#70]
Unhandled rejection SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/enduro/libs/actions/developer_start.js:12:21)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /usr/local/lib/node_modules/enduro/libs/linker/linker.js:74:35

enduro installed no problem. my dist is kali linux

**Comment by Gottwik** [comment]
Hey @TheFenixfx , thank you for reporting this. We already had the issue with #68 and decided to support node version 6+.

Is that ok for you? Or do you need node 4 for some reason?

**Comment by TheFenixfx** [comment]
Is ok, im using enduro from windows now. I had to use a trick in windows ( copy the stylesheet from the mirror theme online, create the _src folder and put it there) because sass for some reason did not create the file. Just leaving the info here to help. Nice app ^^.

**Comment by Gottwik** [comment]
yea, I fixed the mirror theme as well. We changed the _src folder name to _generated which caused problems with the mirror theme if you had newer enduro installed globally :-/
