### ISSUE TITLE
Afther deployed, there is no 'Add page' link

### ISSUE THREAD

**Issue by archcra** [Gottwik/Enduro#77]
In my dev env, everything works fine. But after deployed, there is no 'Add page' link. And when click 'Manual reload content', there are errors in the browser console.

<img width="1040" alt="blog-issue-1" src="https://user-images.githubusercontent.com/6466550/27998939-1a9c5ebc-6549-11e7-95d5-0061207242d5.png">

<img width="1201" alt="blog-issue-2" src="https://user-images.githubusercontent.com/6466550/27998942-21ffb23a-6549-11e7-8467-869a7236b0e4.png">

The console message of browser: 

youshiyou.de/:7 GET http://youshiyou.de/_prebuilt/_settings.css 
jquery.min.js:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.min.js:4
ajax @ jquery.min.js:4
n._evalUrl @ jquery.min.js:4
ua @ jquery.min.js:3
append @ jquery.min.js:3
n.fn.(anonymous function) @ jquery.min.js:3
(anonymous) @ extension_service.js:11
processQueue @ angular.js:16104
(anonymous) @ angular.js:16120
$eval @ angular.js:17378
$digest @ angular.js:17191
$apply @ angular.js:17486
done @ angular.js:11637
completeRequest @ angular.js:11843
requestLoaded @ angular.js:11776
VM1458:1 this gets injected to admin
angular.js:11821 GET http://youshiyou.de/admin_api/refresh?sid=ngPSQj1YoRX_YkWC9IYhHC0aPqJ74zqt 403 (Forbidden)
(anonymous) @ angular.js:11821
sendReq @ angular.js:11582
serverRequest @ angular.js:11292
processQueue @ angular.js:16104
(anonymous) @ angular.js:16120
$eval @ angular.js:17378
$digest @ angular.js:17191
(anonymous) @ angular.js:17417
completeOutstandingRequest @ angular.js:5912
(anonymous) @ angular.js:6191
juice_service.js:23 connection to api failed
angular.js:13642 TypeError: Cannot read property 'data' of undefined
    at juice_service.js:38
    at processQueue (angular.js:16104)
    at angular.js:16120
    at Scope.$eval (angular.js:17378)
    at Scope.$digest (angular.js:17191)
    at angular.js:17417
    at completeOutstandingRequest (angular.js:5912)
    at angular.js:6191

**Comment by Gottwik** [comment]
Can you check which enduro version you are running(`enduro --version`)? Where is your website being deployed? I suggest adding enduro version to package.json, otherwise the server can pick up whichever version it has cached.

**Comment by archcra** [comment]
ubuntu@MAIZE:/mnt/diskc/cms$ enduro --version
1.4.25

**Comment by Gottwik** [comment]
@archcra Hey, could you please check if you still have this issue?

**Comment by archcra** [comment]
I'll try it again soon.
In fact, I am now updating the Enduro version on my Server, but, due to network (GFW) issue, I got error during update. When network is OK, I will do it immediately.

**Comment by archcra** [comment]
After upgrade and re-create a new project (with mirror theme), there was still no luck (On server's terminal):
TypeError: Cannot set property 'juicebox_enabled' of undefined

The following is what I did:

ubuntu@MAIZE:/mnt/diskc/cms/home-maize$ sudo npm install enduro -g

$ enduro --version
1.4.37

$ enduro theme mirror

Enduro theme service—~—————————————————┐
│ getting info for 'mirror' theme                        ✓ │
? choose project name: foo-cms
? choose your admin login: maize
? choose your admin password: [hidden]
│ downloading and extracting theme                       ✓ │
│ setting up admin credentials                           ✓ │
│ getting project dependencies                           ✓ │
│ installing npm dependencies                            ✓ │
│ installing bower dependencies                          ✓ │
│ starting enduro                                        ✓ │
├——————————————————————————————————————————————————————————┤
│                                                          │
│ your project was created successfully                    │
│                                                          │
│ to start your project again, just cd                     │
│ into project directory and run                           │
│                                                          │
│     $ enduro                                             │
│                                                          │
│ the browser should open soon                           ✓ │




$ enduro admin add maize mditip1

┌—————————————~—ENDURO - Creating admin user—~—————————————┐
│ Username:                                                │
│     maize                                                │
│                                                          │
│ Password:                                                │
│     mditip1                                              │
│                                                          │
└——————————————————————————————————————————————————————————┘
ubuntu@MAIZE:/mnt/diskc/cms/foo-cms$ enduro start
[15:55:07 | +     3.4] Production server started at port 5000
[15:55:07 | +    0.11] Render started
[15:55:07 | +     0.1] js compiling not enabled, add babel options to enduro.json to enable
[15:55:07 | +       0] Sass compiling started
[15:55:09 | +    1.31] Sass compiling finished
Error: ENOENT: no such file or directory, stat '/mnt/diskc/cms/foo-cms/_generated/_prebuilt/_settings.css.html'
    at Error (native)
TypeError: Cannot set property 'juicebox_enabled' of undefined
    at api_call.call (/usr/lib/node_modules/enduro/libs/admin_api/get_application_settings.js:14:40)
    at admin_api.call (/usr/lib/node_modules/enduro/libs/admin_api.js:20:38)
    at /usr/lib/node_modules/enduro/libs/enduro_server/enduro_server.js:97:14
    at Layer.handle [as handle_request] (/usr/lib/node_modules/enduro/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:137:13)
    at multipart (/usr/lib/node_modules/enduro/node_modules/connect-multiparty/index.js:47:63)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/enduro/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:137:13)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at Route.dispatch (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/enduro/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/enduro/node_modules/express/lib/router/index.js:281:22
    at param (/usr/lib/node_modules/enduro/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/lib/node_modules/enduro/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/lib/node_modules/enduro/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/index.js:275:10)
    at /usr/lib/node_modules/enduro/libs/enduro_server/enduro_server.js:42:2



$ cat /etc/issue
Ubuntu 14.04.4 LTS \n \l

$ node -v
v6.11.0

$ npm -v
3.10.10

**Comment by archcra** [comment]
I found other issues when run app on Server (Ubuntu). One of them is:

.hbs does not render global variables.

**Comment by archcra** [comment]
I hope when such exception occurs, there are errors shown. Or else, I'm afraid I can do nothing.

**Comment by rkmax** [comment]
@Gottwik I also have this issue with the version 1.4.45 (project was created with 1.4.44) in my case I have not deployed yet, as soon I open the :5000/admin page (after login) the error appear on console

```
TypeError: Cannot set property 'juicebox_enabled' of undefined
    at api_call.call (/home/rkmax/.nvm/versions/node/v9.2.0/lib/node_modules/enduro/libs/admin_api/get_application_settings.js:14:40)
...
```
