### ISSUE TITLE
Install theme on Ubuntu failed

### ISSUE THREAD

**Issue by archcra** [Gottwik/Enduro#78]
Full message as following:

ubuntu@MAIZE:/mnt/diskc/cms$ enduro theme

┌—————————————————~—Enduro theme service—~—————————————————┐
? choose a theme mirror
│ getting info for 'mirror' theme                        ✓ │
? choose project name: maize-cms
? choose your admin login: admin
? choose your admin password: [hidden]
│ downloading and extracting theme                       ✓ │
│ setting up admin credentials                           ✓ │
│ getting project dependencies                           ✓ │
/usr/lib/node_modules/enduro/libs/theme_manager/theme_manager.js:123
						if (err) { console.log(error) }
						                       ^

ReferenceError: error is not defined
    at /usr/lib/node_modules/enduro/libs/theme_manager/theme_manager.js:123:30
    at cb (/usr/lib/node_modules/enduro/node_modules/npm/lib/install.js:232:16)
    at /usr/lib/node_modules/enduro/node_modules/npm/lib/install.js:319:7
    at LOOP (/usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
    at /usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at Object.Installer.printInstalled (/usr/lib/node_modules/enduro/node_modules/npm/lib/install.js:717:28)
    at Array.<anonymous> (/usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at Object.Installer.printWarnings (/usr/lib/node_modules/enduro/node_modules/npm/lib/install.js:712:3)
    at Array.<anonymous> (/usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at Object.Installer.saveToDependencies (/usr/lib/node_modules/enduro/node_modules/npm/lib/install.js:605:28)
    at Array.<anonymous> (/usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at exports.removeExtraneous (/usr/lib/node_modules/enduro/node_modules/npm/lib/install/deps.js:331:3)
    at Object.Installer.pruneIdealTree (/usr/lib/node_modules/enduro/node_modules/npm/lib/install.js:411:10)
    at Array.<anonymous> (/usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at Object.postInstallSteps.push (/usr/lib/node_modules/enduro/node_modules/npm/lib/install.js:297:61)
    at Array.<anonymous> (/usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at Object.Installer.finishTracker (/usr/lib/node_modules/enduro/node_modules/npm/lib/install.js:344:3)
    at Array.<anonymous> (/usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at Object.Installer.runPostinstallTopLevelLifecycles (/usr/lib/node_modules/enduro/node_modules/npm/lib/install.js:586:28)
    at Array.<anonymous> (/usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at asyncMap (/usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/async-map.js:27:18)
    at Object.Installer.commit (/usr/lib/node_modules/enduro/node_modules/npm/lib/install.js:557:3)
    at Array.<anonymous> (/usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/lib/node_modules/enduro/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at Object.Installer.finishTracker (/usr/lib/node_modules/enduro/node_modules/npm/lib/install.js:344:3)
ubuntu@MAIZE:/mnt/diskc/cms$ node -v
v6.11.0

**Comment by Gottwik** [comment]
Hey, thank you for reporting this. Found some problems with error logging, could you please reinstall enduro and rerun the `enduro theme` command?

**Comment by archcra** [comment]
Marvelous! I executed 'enduro theme' without any error, and there was the second theme: enblog, I couldn't wait for trying it. But, sadly, the 'mirror theme' still has the blog issue, that means, after I added files as described in your blog, I failed to get the blog work:

There are errors on my browser console. I'll try the enblog theme, hope that help.

Browser console messages:

_settings.css Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.min.js:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.min.js:4
(unknown) this gets injected to admin
content_service.js:22 error getting page list
angular.js:13642 TypeError: Cannot read property 'structured' of undefined
    at mainmenu_controller.js:7
    at processQueue (angular.js:16104)
    at angular.js:16120
    at Scope.$eval (angular.js:17378)
    at Scope.$digest (angular.js:17191)
    at Scope.$apply (angular.js:17486)
    at done (angular.js:11637)
    at completeRequest (angular.js:11843)
    at XMLHttpRequest.requestLoaded (angular.js:11776)
(anonymous) @ angular.js:13642
angular.js:13642 TypeError: Cannot read property 'tags' of undefined
    at new <anonymous> (http://119.254.100.30:5000/admin/assets/js/controllers/cms_editor_controller.js:127:35)
    at Object.invoke (http://119.254.100.30:5000/admin/assets/vendor/angular/angular.js:4708:19)
    at $controllerInit (http://119.254.100.30:5000/admin/assets/vendor/angular/angular.js:10177:34)
    at nodeLinkFn (http://119.254.100.30:5000/admin/assets/vendor/angular/angular.js:9096:34)
    at compositeLinkFn (http://119.254.100.30:5000/admin/assets/vendor/angular/angular.js:8459:13)
    at publicLinkFn (http://119.254.100.30:5000/admin/assets/vendor/angular/angular.js:8339:30)
    at Object.link (http://119.254.100.30:5000/admin/assets/vendor/angular/angular.js:26021:38)
    at http://119.254.100.30:5000/admin/assets/vendor/angular/angular.js:1266:18
    at invokeLinkFn (http://119.254.100.30:5000/admin/assets/vendor/angular/angular.js:9757:9)
    at nodeLinkFn (http://119.254.100.30:5000/admin/assets/vendor/angular/angular.js:9156:11) <div class="currently-editing-page ng-scope" ng-include="inner_page" ng-controller="pagesplit_controller">
(anonymous) @ angular.js:13642
:5000/admin_api/get_cms?filename=maize-cms%2Fcms%2Findex&sid=21U8udLrw9OqcdyCHJDwGx2i5BSWE60E Failed to load resource: the server responded with a status of 401 (Unauthorized)
:5000/admin_api/get_cultures?sid=21U8udLrw9OqcdyCHJDwGx2i5BSWE60E Failed to load resource: the server responded with a status of 401 (Unauthorized)
:5000/admin/#/login:1 This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
angular.js:13642 TypeError: Cannot read property 'tags' of undefined
    at new <anonymous> (http://119.254.100.30:5000/admin/assets/js/controllers/cms_editor_controller.js:127:35)
    at Object.invoke (http://119.254.100.30:5000/admin/assets/vendor/angular/angular.js:4708:19)
    at $controllerInit (http://119.254.100.30:5000/admin/assets/vendor/angular/angular.js:10177:34)
    at nodeLinkFn (http://119.254.100.30:5000/admin/assets/vendor/angular/angular.js:9096:34)
    at compositeLinkFn (http://119.254.100.30:5000/admin/assets/vendor/angular/angular.js:8459:13)
    at publicLinkFn (http://119.254.100.30:5000/admin/assets/vendor/angular/angular.js:8339:30)
    at Object.link (http://119.254.100.30:5000/admin/assets/vendor/angular/angular.js:26021:38)
    at http://119.254.100.30:5000/admin/assets/vendor/angular/angular.js:1266:18
    at invokeLinkFn (http://119.254.100.30:5000/admin/assets/vendor/angular/angular.js:9757:9)
    at nodeLinkFn (http://119.254.100.30:5000/admin/assets/vendor/angular/angular.js:9156:11) <div class="currently-editing-page ng-scope" ng-include="inner_page" ng-controller="pagesplit_controller">
(anonymous) @ angular.js:13642
angular.js:13642 TypeError: Cannot read property 'add' of undefined
    at add_culture_switch_hotkey (cms_editor_controller.js:32)
    at cms_editor_controller.js:42
    at processQueue (angular.js:16104)
    at angular.js:16120
    at Scope.$eval (angular.js:17378)
    at Scope.$digest (angular.js:17191)
    at Scope.$apply (angular.js:17486)
    at done (angular.js:11637)
    at completeRequest (angular.js:11843)
    at XMLHttpRequest.requestLoaded (angular.js:11776)
(anonymous) @ angular.js:13642

**Comment by archcra** [comment]
I think the error is duplicated as issue #77, so I close the issue.
