### ISSUE TITLE
theme enblog installing failed

### ISSUE THREAD

**Issue by archcra** [Gottwik/Enduro#81]
Messages on my term as:

ubuntu@MAIZE:/mnt/diskc/cms$ enduro theme enblog

┌—————————————————~—Enduro theme service—~—————————————————┐
│ getting info for 'enblog' theme                        ✓ │
? choose project name: ablog
? choose your admin login: admin
? choose your admin password: [hidden]
│ downloading and extracting theme                       ✓ │
│ setting up admin credentials                           ✓ │
│ getting project dependencies                           ✓ │
│ installing npm dependencies                            ✓ │
│ installing bower dependencies                          ✓ │
│ starting enduro                                        ⠴ │
/usr/lib/node_modules/enduro/node_modules/gulp-iconfont-css/index.js:112
						throw new gutil.PluginError(PLUGIN_NAME, 'Error in template: ' + err.message);
						^
Error: Error in template: ENOENT: no such file or directory, open 'assets/fonticons/icons_template.scss'
ubuntu@MAIZE:/mnt/diskc/cms$

**Comment by archcra** [comment]
ubuntu@MAIZE:/mnt/diskc/cms$ enduro --version
1.4.25

**Comment by archcra** [comment]
ubuntu@MAIZE:/mnt/diskc/cms$ node --version
v6.11.0
ubuntu@MAIZE:/mnt/diskc/cms$ npm --version
3.10.10

**Comment by Gottwik** [comment]
Hey, thank you for reporting this. Would you mind updating enduro and trying again please? I believe I fixed it

**Comment by archcra** [comment]
ubuntu@MAIZE:/mnt/diskc/cms$ sudo npm i enduro -g

ubuntu@MAIZE:/mnt/diskc/cms$ enduro --version
1.4.29

ubuntu@MAIZE:/mnt/diskc/cms$ enduro theme

┌—————————————————~—Enduro theme service—~—————————————————┐
? choose a theme enblog
│ getting info for 'enblog' theme                        ✓ │
? choose project name: ablog
? choose your admin login: admin
? choose your admin password: [hidden]
│ downloading and extracting theme                       ✓ │
│ setting up admin credentials                           ✓ │
│ getting project dependencies                           ✓ │
│ installing npm dependencies                            ✓ │
│ installing bower dependencies                          ✓ │
│ starting enduro                                        ✓ │
├——————————————————————————————————————————————————————————┤
│                                                          │
│ your project was created successfully                    │
│                                                          │
│ to start your project again, just cd                     │
│ into project directory and run                           │
│                                                          │
│     $ enduro                                             │
│                                                          │
│ the browser should open soon                           ✓ │
└——————————————————————————————————————————————————————————┘

Error: ENOENT: no such file or directory, stat '/mnt/diskc/cms/ablog/_generated/_prebuilt/_settings.css.html'
    at Error (native)
TypeError: Cannot set property 'juicebox_enabled' of undefined
    at api_call.call (/usr/lib/node_modules/enduro/libs/admin_api/get_application_settings.js:14:40)
    at admin_api.call (/usr/lib/node_modules/enduro/libs/admin_api.js:20:38)
    at /usr/lib/node_modules/enduro/libs/enduro_server/enduro_server.js:97:14
    at Layer.handle [as handle_request] (/usr/lib/node_modules/enduro/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:137:13)
    at multipart (/usr/lib/node_modules/enduro/node_modules/connect-multiparty/index.js:47:63)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/enduro/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:137:13)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:131:14)
    at Route.dispatch (/usr/lib/node_modules/enduro/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/enduro/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/enduro/node_modules/express/lib/router/index.js:281:22
    at param (/usr/lib/node_modules/enduro/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/lib/node_modules/enduro/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/lib/node_modules/enduro/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/index.js:275:10)
    at /usr/lib/node_modules/enduro/libs/enduro_server/enduro_server.js:42:2
    at Layer.handle [as handle_request] (/usr/lib/node_modules/enduro/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/lib/node_modules/enduro/node_modules/express/lib/router/index.js:317:13)
    at /usr/lib/node_modules/enduro/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/node_modules/enduro/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/index.js:275:10)
    at cors (/usr/lib/node_modules/enduro/node_modules/cors/lib/index.js:185:7)
    at /usr/lib/node_modules/enduro/node_modules/cors/lib/index.js:221:17
    at originCallback (/usr/lib/node_modules/enduro/node_modules/cors/lib/index.js:211:15)
    at /usr/lib/node_modules/enduro/node_modules/cors/lib/index.js:216:13
    at optionsCallback (/usr/lib/node_modules/enduro/node_modules/cors/lib/index.js:196:9)
    at corsMiddleware (/usr/lib/node_modules/enduro/node_modules/cors/lib/index.js:201:7)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/enduro/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/lib/node_modules/enduro/node_modules/express/lib/router/index.js:317:13)
    at /usr/lib/node_modules/enduro/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/node_modules/enduro/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/enduro/node_modules/express/lib/router/index.js:275:10)
    at cookieParser (/usr/lib/node_modules/enduro/node_modules/cookie-parser/index.js:70:5)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/enduro/node_modules/express/lib/router/layer.js:95:5)

**Comment by Gottwik** [comment]
I believe this was theme related but has since been fixed. Please reopen if persists
