### ISSUE TITLE
Maybe mistake in document: http://www.endurojs.com/docs/app

### ISSUE THREAD

**Issue by archcra** [Gottwik/Enduro#87]
This line of sample code: 
        res.send(Math.random())

seems to be:
        res.send(200, Math.random())

**Comment by Gottwik** [comment]
Is it?

The sample outputs random value to show that the page will be different every time you load it. I believe if you don't provide a response status, it's 200.

http://expressjs.com/en/api.html#res.send

**Comment by archcra** [comment]
I followed the document twice, with the same error on term:

express deprecated res.send(status): Use res.sendStatus(status) instead app/app.js:7:12
_http_server.js:192
    throw new RangeError(`Invalid status code: ${statusCode}`);
    ^

RangeError: Invalid status code: 0
    at ServerResponse.writeHead (_http_server.js:192:11)
    at ServerResponse.writeHead (/usr/local/lib/node_modules/enduro/node_modules/on-headers/index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.OutgoingMessage.end (_http_outgoing.js:574:10)
    at writeend (/usr/local/lib/node_modules/enduro/node_modules/express-session/index.js:261:22)
    at Immediate.onsave (/usr/local/lib/node_modules/enduro/node_modules/express-session/index.js:335:11)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)



With the code as my suggestion, I got the expected result.

**Comment by Gottwik** [comment]
Hey, you are right, after all. I think it doesn't allow to send numbers.

I changed it to:
`res.send(Math.random().toString())`

That should work, right?

**Comment by Gottwik** [comment]
Hey, I will go ahead and close this ticket. @archcra feel free to re-open if you feel the `.toString` will not get it done.
