### ISSUE TITLE
New projects don't work — enduro writes to and reads from wrong folders

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [Gottwik/Enduro#91]
It is related to this issue: https://github.com/Gottwik/Enduro/issues/81#issuecomment-314957889
I created a new project and see similar errors like in that issue:
```
[23:25:52 | +    8.55] developer start
[23:25:52 | +    0.23] Render started
[23:25:52 | +    0.01] Sass compiling started
[23:25:52 | +    0.05] Sass compiling finished
[23:25:52 | +    0.09] Render finished
[23:25:52 | +    0.03] browsersync started
[23:25:52 | +    0.05] production server starting
[23:25:52 | +    0.02] Production server started at port 5000
Error: ENOENT: no such file or directory, stat 'D:\_namespace\_comigogames\comigogames\components\_generated\_prebuilt\_settings.css.html'
TypeError: Cannot set property 'juicebox_enabled' of undefined
    at api_call.call (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\libs\admin_api\get_application_settings.js:14:40)
    at admin_api.call (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\libs\admin_api.js:20:38)
    at C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\libs\enduro_server\enduro_server.js:97:14
    at Layer.handle [as handle_request] (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\route.js:137:13)
    at multipart (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\connect-multiparty\index.js:47:63)
    at Layer.handle [as handle_request] (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\route.js:137:13)
    at next (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\route.js:131:14)
    at Route.dispatch (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\index.js:281:22
    at param (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\index.js:354:14)
    at param (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\index.js:410:3)
    at next (C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\node_modules\express\lib\router\index.js:275:10)
    at C:\Users\Космо\AppData\Roaming\npm\node_modules\enduro\libs\enduro_server\enduro_server.js:42:2
```
But I still can enter the admin UI, though that's what I see:

![image](https://user-images.githubusercontent.com/3174357/28247141-082cd19a-6a7f-11e7-9703-e76e6eb277e9.png)

So css file is being looked for in `http://localhost:5000/_prebuilt/_settings.css`, and cms outline is empty.

If I go to the `project_folder\components\_generated\_prebuilt\cmslist.json`, I see this: 
```
{"structured":{},"flat":[]}
```
And here comes the fist question in my head: WTF it is doing here? It mustn't be located in `components` folder. If I go to `project_folder\_generated\_prebuilt\`, I can see `settings.css`, a valid-looking `cmslist.json` and `_cultures.json`.

Also GET requests to localhost:3000/ fail with message `Cannot GET /`

**Comment by CosmoMyzrailGorynych** [comment]
These requests return empty cms lists, like in `components` folder:
![image](https://user-images.githubusercontent.com/3174357/28247243-e62db170-6a80-11e7-9fed-fb7617cadfac.png)

**Comment by CosmoMyzrailGorynych** [comment]
Haha I just ran `enduro dev` on a wrong folder. Can't imagine how I could miss like that.
